### ISSUE TITLE
Update to NestJS 7.0

### ISSUE THREAD

**Issue by wSedlacek** [EndyKaufman/typegraphql-prisma-nestjs#2]
NestJS decided to reimplement all the features from scratch in type-graphql but using the same API meaning that every `type-graphql` import needs to be changed to `@nestjs/graphql` and the unimplemented decorators like `FieldResolver` and `Arg` need to be removed from the imports

Source: https://docs.nestjs.com/migration-guide#graphql

> GraphQL#
> In the version 6 major release of NestJS, we introduced the code-first approach as a compatibility layer between the type-graphql package and the @nestjs/graphql module. Eventually, our team decided to reimplement all the features from scratch due to a lack of flexibility. To avoid numerous breaking changes, the public API is backward-compatible and may resemble type-graphql.
> 
> In order to migrate your existing application, simply rename all the type-graphql imports to the @nestjs/graphql.
>

**Comment by EndyKaufman** [comment]
hi! changes in nestjs 7 very bad ( because i use dto with type-graphql decorators not only on backend, i use it and in frontend application with mono repository

nestjs decorator use many node dependencies anf file system utils, now i try resolve this problem

![image](https://user-images.githubusercontent.com/4127109/77246753-155dbb00-6c4c-11ea-85e7-a01aef7ebef2.png)

**Comment by EndyKaufman** [comment]
thank you, solved and publish in new version
